TrajectoryPlannerROS:
  max_vel_x: 0.5
  min_vel_x: 0.1
  max_vel_theta: 1.5
  min_in_place_vel_theta: 0.7

  acc_lim_theta: 3.2
  acc_lim_x: 0.5
  acc_lim_y: 0
  
  pdist_scale: 0.9

  holonomic_robot: false
